### PR TITLE
Fix default legacyTranslate value incosistency

### LINKED ISSUE #199: Svelte: translate applied twice when initial position value provided
When no `legacyTranslate` value is provided and an initial value for `position` is set, translate is applied twice: once as translate, second as transform: translate3d. [Repro](https://svelte.dev/playground/ef04883cebdc4c4bba61e744b2d7ed47?version=5.19.7)

This is being caused by a mismatch of default value for `legacyTranslate`. Here, when initializing draggable instance, the fallback is `false`:
https://github.com/PuruVJ/neodrag/blob/61e34331987a48a49accbe62370867248c35fc07/packages/core/src/index.ts#L275-L280

Here, in `update`, it defaults to `true` instead:
https://github.com/PuruVJ/neodrag/blob/61e34331987a48a49accbe62370867248c35fc07/packages/core/src/index.ts#L632-L644

Thus, when `legacyTranslate` is not provided, two different translate styles are being applied. 99% sure it's the reason for #123 and probably #194 too.
I don't know what is the intended default value, as it is false in jsDoc: https://github.com/PuruVJ/neodrag/blob/61e34331987a48a49accbe62370867248c35fc07/packages/core/src/index.ts#L88
and true in docs:
https://github.com/PuruVJ/neodrag/blob/61e34331987a48a49accbe62370867248c35fc07/docs/src/documentation/options/legacyTranslate/%2Boption.mdx?plain=1#L4

### PR DESCRIPTION
**Pull request by Wiblz**
Fix #199 and possibly #123 and #194.
Assuming intended default value to be `false` based on 0cead8701f132670bd5618ceeb8fdee8e9a3ad27

### CODE REVIEW

File: packages/core/src/index.ts [hunk 1]
```diff
@@ -641,7 +641,7 @@ export function draggable(node: HTMLElement, options: DragOptions = {}) {
 			applyUserSelectHack = options.applyUserSelectHack ?? true;
 			grid = options.grid;
 			gpuAcceleration = options.gpuAcceleration ?? true;
-			legacyTranslate = options.legacyTranslate ?? true;
+			legacyTranslate = options.legacyTranslate ?? false;
```
Comment (PuruVJ) [inline packages/core/src/index.ts:644]: It seems I missed this 😅

**Comment by PuruVJ** [comment]
This looks amazing, thanks! Can you please add a changeset? In the root, `pnpm changeset`, choose all the `@neodrag/*` packages, select patch, write a short message about the fix, and commir

**Comment by PuruVJ** [comment]
Thanks a lot!
